console.log("wtf");
document.writeln('		<div id="siteHeader"> <!-- Pjesa statike -->');
document.writeln('			<div class="logo">');
document.writeln('			<figure class="figureSyle">');
document.writeln('				  <img src="images/logo.png" width="70px" height="70px" alt="Logo nuk u gjet!" />');
document.writeln('				  <figcaption>Nje vend argetimi per te gjithe</figcaption>');
document.writeln('			</figure>');
document.writeln('			</div>');
document.writeln('			<div class="rightSideBar">');
document.writeln('				<div class="Search">');
document.writeln('					<input type="text" placeholder="Search this website..." />');
document.writeln('					<input class="buttonN" type="submit" value="Search">');
document.writeln('				</div><br /><br />');
document.writeln('				<div id="pagesMenu">');
document.writeln('							<ul>');
document.writeln('								<li> <a href="#">Live Streaming</a> </li>');
document.writeln('								<li> <a href="filmat.html">Filma</a> </li>');
document.writeln('								<li> <a href="serialet.html">Seriale</a> </li>');
document.writeln('								<li> <a href="#">Anime</a> </li>');
document.writeln('							</ul>');
document.writeln('				</div>');
document.writeln('			</div>');
document.writeln('		</div>');